### PR TITLE
Feature/metamap implementation

### PR DESCRIPTION
**Pull request by juandatorr99**
## Summary
Add metamap implementation SDK, added id to queries and changes userId for authId. 
The status needs to be implemented still.

TODO: @manu-yaff 
  Implement Cancel KYC enpoint when the user cancels 
  Show in the dashboard the status of the verification

## Requirements
Test it on the branch Feature/OINK-844 of the backend
make sure you reaplace your `.env` with the latest version

## Type of change
- [ x ] feature
- [ ] hotfix
- [ ] fix
- [ ] refactor
- [ ] chore
- [ ] docs

## How to test?
Run the app, login and try to make a deposit through the transfer button it should take you to the KYC and after you finalize it should show you a message of success.

## How has this been tested?

- [ ] Check if the kycStatus in the table changes

## Screenshots
_add screenshots if need it_

## Checklist (for the reviewer)

- [ ] Does the code compile without errors or warnings?
- [ ] Does the PR is free of merge conflicts?
- [ ] Does the UI is responsive?
- [ ] Is the PR modular?

### CODE REVIEW

**Comment by juandatorr99** [comment]
Task linked: [OINK-844 Change kycVerified in user to a String state](https://app.clickup.com/t/24497898/OINK-844)

**Comment by manu-yaff** [comment]
Hay conflictos @juandatorr99

**Review by manu-yaff — CHANGES_REQUESTED** [review]
Hay conflictos @juandatorr99

**Review by kiwis08 — APPROVED** [review]
Fuera del archivo vacío resident_form_screen, todo lo veo bien

**Comment by manu-yaff** [comment]
@juandatorr99 cuando lo pruebo con el simulator me sale este error:
imagen

y cuando lo pruebo en el teléfono me da este:
imagen

**Pull request merged**
